### ISSUE TITLE
add high-water marks to plotting functionality

### ISSUE THREAD

**Issue by ghost** [noaa-ocs-modeling/autoval#1]
@saeed-moghimi-noaa

**Comment by saeed-moghimi-noaa** [comment]
Assigned to @ps2epsi  @GeorgiosBritzolakisNOAAFederal

**Comment by saeed-moghimi-noaa** [comment]
@GeorgiosBritzolakisNOAAFederal  @gseroka 

George,

Please start working on including HWM scatter plot to the autoval package. Happy to chat with you on that.

Thanks,
-Saeed

**Comment by zacharyburnettNOAA** [comment]
@GeorgiosBritzolakisNOAAFederal I have added an interface to the high water marks API in the https://github.com/zacharyburnettNOAA/StormEvents library. The current implementation (originally written by Jaime) takes a storm name and year as input and outputs a dataframe / CSV of the high water marks data based on filter criteria

**Comment by janahaddad** [comment]
Closing -- no longer need this functionality in Autoval
