### ISSUE TITLE
Tested: autoval 3.0 (the version of Apr 2, 2024) run for stofs-atl-3d

### ISSUE THREAD

**Issue by yangz888** [noaa-ocs-modeling/autoval#6]
@AtiehAlipour-NOAA 
The autoval package works well. Please see the results (period of 20240109120600 ... 20240114120000)  at https://noaa-nos-stofs3d-pds.s3.amazonaws.com/STOFS-3D-Atl/para/nwm3_autoval_v3/post_processing/autoval/autoval.stofs3d.atl.20240110_tmp5/index.htm. All look good!

Thanks, Atieh!

**Comment by AtiehAlipour-NOAA** [comment]
@yangz888 Wonderful. Thanks for the update.
